# NOTE: this will be converted to a namespace secret store in the future after the error below is fixed:
#failed to create resource: admission webhook "validate.secretstore.external-secrets.io" denied the request: namespace should either be empty or match the namespace of the SecretStore for a namespaced SecretStore

{{- if .Values.secrets.enabled }}
# Cluster Secret Store
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.environment | lower }}-{{ .Values.services.webService.name | lower }}
spec:
  provider:
    infisical:
      hostAPI: http://infisical.infisical.svc.cluster.local:8080/api
      auth:
        universalAuthCredentials:
          clientId:
            name: universal-infisical-credentials
            namespace: infisical
            key: CLIENT_ID
          clientSecret:
            name: universal-infisical-credentials
            namespace: infisical
            key: CLIENT_SECRET
      secretsScope:
        projectSlug: {{ .Values.environment | lower }}-{{ .Values.project.name | lower }}
        environmentSlug: {{ .Values.environment | lower }}
        {{- if .Values.secrets.secretStorePath }}
        secretsPath: /{{ .Values.secrets.secretStorePath | lower }}
        {{- else }}
        secretsPath: /{{ .Values.services.webService.name | lower }}
        {{- end }}
        recursive: true
        expandSecretReferences: false

---
# External Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.environment | lower }}-{{ .Values.services.webService.name | lower }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  secretStoreRef:
    name: {{ .Values.environment | lower }}-{{ .Values.services.webService.name | lower }}
    kind: ClusterSecretStore
  refreshInterval: 1m
  target:
    name: {{ .Values.environment | lower }}-{{ .Values.services.webService.name | lower }}
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        name:
          regexp: ".*"
{{- end }}
